version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres-1
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - '5432:5432'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: 0601-pgadmin4-1
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
