streams:
api:
  origin: "*"
webrtc:
  ice_servers:
    - urls: [stun:stun.l.google.com:19302]
    - urls: [turn:176.57.70.104:3478]
      username: test
      credential: test123
ffmpeg:
  def_args: "-fflags nobuffer -flags low_delay -strict experimental -rtsp_transport tcp"